### ISSUE TITLE
Error in Pool.h (std::max issue)

### ISSUE THREAD

**Issue by bojjenclon** [Lusito/ecstasy#1]
While trying to add ECS-tasy to a project, I got the following error:
error C2589: '(' : illegal token on right side of '::'  include\ecstasy\utils\Pool.h    93  1

After a bit of Google-ing it appears to be related to the fact that my project uses windows.h, but after trying multiple solutions (#define NOMINMAX, parentheses, etc.) I just can't seem to get the library to work. Any advice on how to go about fixing it?

Edit:
I seem to have gotten it working by adding:
# ifdef max
# undef max
# endif

**Comment by Lusito** [comment]
Wow, why am I not getting notified about issues by Github ?
Sorry about the delay.

Try adding the NOMINMAX as compiler flag/define instead of a header file.
min/max macros should not be used anyway, so you're better off completely disabling them.

**Comment by Lusito** [comment]
Btw, let me know about your experience.
I haven't had the chance yet to try it in a real project.

**Comment by Lusito** [comment]
I've just had the same issue in one of my projects, and adding the define as a compiler flag fixed it.
